name: kobodict
kind: pipeline
type: docker

steps:
- name: test
  image: golang:1.13-buster
  commands:
  - go test -cover -v ./kobodict
- name: bench
  image: golang:1.13-buster
  commands:
  - go test -bench=. -benchmem ./kobodict

exclude:
  event: [promote]

---

name: dictgen
kind: pipeline
type: docker

steps:
- name: test
  image: golang:1.13-buster
  commands:
  - go test -cover -v ./dictgen

exclude:
  event: [promote]
