name: kobodict
kind: pipeline
type: docker

steps:
- name: test
  image: golang:1.13-buster
  commands:
  - go test -cover -v ./kobodict
- name: bench
  image: golang:1.13-buster
  commands:
  - go test -bench=. -benchmem ./kobodict

trigger:
  event:
    exclude: [promote]

---

name: dictgen
kind: pipeline
type: docker

steps:
- name: test
  image: golang:1.13-buster
  commands:
  - go test -cover -v ./dictgen

trigger:
  event:
    exclude: [promote]

---

name: marisa
kind: pipeline
type: docker

steps:
- name: generate
  image: golang:1.13-buster
  commands:
  - go generate ./marisa
  - git status --porcelain ./marisa/libmarisa.cc ./marisa/marisa.h
  - '[ ! -n "$(git status --porcelain ./marisa/libmarisa.cc ./marisa/marisa.h)" ] || { echo "Error: Generated files are not up to date, please run go generate and commit the result."; false; }'
- name: test
  image: golang:1.13-buster
  commands:
  - apt-get update -qqy && apt-get install -qqy swig
  - go test -v ./marisa
- name: build-windows-386
  image: docker.elastic.co/beats-dev/golang-crossbuild:1.13.6-main
  command: [
    "--platforms", "windows/386",
    "--build-cmd", "apt-get update -qqy && apt-get install -qqy swig && CGO_ENABLED=1 go build -x ./marisa",
  ]
  depends_on: [test]
- name: build-linux-amd64
  image: docker.elastic.co/beats-dev/golang-crossbuild:1.13.6-main
  command: [
    "--platforms", "linux/amd64",
    "--build-cmd", "apt-get update -qqy && apt-get install -qqy swig && CGO_ENABLED=1 go build -x ./marisa",
  ]
  depends_on: [test]
- name: build-linux-arm
  image: docker.elastic.co/beats-dev/golang-crossbuild:1.13.6-arm
  command: [
    "--platforms", "linux/armv6",
    "--build-cmd", "apt-get update -qqy && apt-get install -qqy swig && CGO_ENABLED=1 go build -x ./marisa",
  ]
  depends_on: [test]
- name: build-darwin-amd64
  image: docker.elastic.co/beats-dev/golang-crossbuild:1.13.6-darwin
  command: [
    "--platforms", "darwin/amd64",
    "--build-cmd", "apt-get update -qqy && apt-get install -qqy swig && CGO_ENABLED=1 go build -x ./marisa",
  ]
  depends_on: [test]

trigger:
  event:
    exclude: [promote]

---

name: gotdict-convert
kind: pipeline
type: docker

steps:
- name: build
  image: golang:1.13-buster
  commands:
  - go build -o gotdict-convert ./examples/gotdict-convert
- name: convert
  image: golang:1.13-buster
  commands:
  - git clone https://github.com/wjdp/gotdict
  - git -C gotdict checkout 0a675ef59b5068a91315d594f807dc8d9ae4a777
  - ./gotdict-convert
  - wc -c gotdict.df
# TODO: upload

trigger:
  event:
    exclude: [promote]
