name: kobodict
kind: pipeline
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: golang:1.13-buster
  commands:
  - apt-get update -qqy && apt-get install -qqy swig
  - go test -cover -v ./kobodict
- name: bench
  image: golang:1.13-buster
  commands:
  - apt-get update -qqy && apt-get install -qqy swig
  - go test -bench=. -benchmem ./kobodict

trigger:
  event:
    exclude: [promote]

---

name: dictgen
kind: pipeline
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: golang:1.13-buster
  commands:
  - apt-get update -qqy && apt-get install -qqy swig
  - go test -cover -v ./dictgen

trigger:
  event:
    exclude: [promote]

---

name: dictgen-cmd
kind: pipeline
type: docker

steps:
- name: build
  image: golang:1.13-buster
  commands:
  - apt-get update -qqy && apt-get install -qqy swig
  - go build -o dictgen-out ./cmd/dictgen
- name: run
  image: golang:1.13-buster
  commands:
  - ./dictgen-out --help

trigger:
  event:
    exclude: [promote]

---

name: dictutil-cmd
kind: pipeline
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: golang:1.13-buster
  commands:
  - apt-get update -qqy && apt-get install -qqy swig
  - go build -o dictutil-out ./cmd/dictutil
- name: run
  image: golang:1.13-buster
  commands:
  - ./dictutil-out help

trigger:
  event:
    exclude: [promote]

---

name: marisa
kind: pipeline
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: generate
  image: golang:1.13-buster
  commands:
  - go generate ./marisa
  - git status --porcelain ./marisa/libmarisa.cc ./marisa/marisa.h
  - '[ ! -n "$(git status --porcelain ./marisa/libmarisa.cc ./marisa/marisa.h)" ] || { echo "Error: Generated files are not up to date, please run go generate and commit the result."; false; }'
- name: test
  image: golang:1.13-buster
  commands:
  - apt-get update -qqy && apt-get install -qqy swig
  - go test -v ./marisa
- name: build-windows-386
  image: docker.elastic.co/beats-dev/golang-crossbuild:1.13.8-main
  command: [
    "--platforms", "windows/386",
    "--build-cmd", "apt-get update -qqy && apt-get install -qqy swig && CGO_ENABLED=1 go build -x ./marisa",
  ]
  depends_on: [test]
- name: build-linux-amd64
  image: docker.elastic.co/beats-dev/golang-crossbuild:1.13.8-main
  command: [
    "--platforms", "linux/amd64",
    "--build-cmd", "apt-get update -qqy && apt-get install -qqy swig && CGO_ENABLED=1 go build -x ./marisa",
  ]
  depends_on: [test]
- name: build-linux-arm
  image: docker.elastic.co/beats-dev/golang-crossbuild:1.13.8-arm
  command: [
    "--platforms", "linux/armv6",
    "--build-cmd", "apt-get update -qqy && apt-get install -qqy swig && CGO_ENABLED=1 go build -x ./marisa",
  ]
  depends_on: [test]
- name: build-darwin-amd64
  image: docker.elastic.co/beats-dev/golang-crossbuild:1.13.8-darwin
  command: [
    "--platforms", "darwin/amd64",
    "--build-cmd", "apt-get update -qqy && apt-get install -qqy swig && CGO_ENABLED=1 go build -x ./marisa",
  ]
  depends_on: [test]

trigger:
  event:
    exclude: [promote]

---

name: gotdict-convert
kind: pipeline
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: golang:1.13-buster
  commands:
  - apt-get update -qqy && apt-get install -qqy swig
  - go build -o gotdict-convert ./examples/gotdict-convert
- name: run
  image: golang:1.13-buster
  commands:
  - ./gotdict-convert --help
- name: convert
  image: golang:1.13-buster
  commands:
  - git clone https://github.com/wjdp/gotdict
  - git -C gotdict checkout 0a675ef59b5068a91315d594f807dc8d9ae4a777
  - ./gotdict-convert -o gotdict.noimg.df
  - ./gotdict-convert -o gotdict.df --images
  - ls -lah gotdict.df
- name: generate
  image: golang:1.13-buster
  commands:
  - apt-get update -qqy && apt-get install -qqy swig
  - go run ./cmd/dictgen -o dicthtml-gt.noimg.zip gotdict.noimg.df
  - go run ./cmd/dictgen -o dicthtml-gt.zip gotdict.df
  - ls -lah dicthtml-gt.zip
- name: upload
  image: curlimages/curl
  entrypoint: ["/bin/bash"]
  commands:
  - "curl --no-progress-meter -F 'file=@gotdict.noimg.df'      'https://api.anonfile.com/upload' | grep -Eo '\"full\": *\"[^\"]+' | cut -d'\"' -f4"
  - "curl --no-progress-meter -F 'file=@dicthtml-gt.noimg.zip' 'https://api.anonfile.com/upload' | grep -Eo '\"full\": *\"[^\"]+' | cut -d'\"' -f4"
  - "curl --no-progress-meter -F 'file=@gotdict.df'      'https://api.anonfile.com/upload' | grep -Eo '\"full\": *\"[^\"]+' | cut -d'\"' -f4"
  - "curl --no-progress-meter -F 'file=@dicthtml-gt.zip' 'https://api.anonfile.com/upload' | grep -Eo '\"full\": *\"[^\"]+' | cut -d'\"' -f4"

depends_on: [dictgen-cmd]

trigger:
  event:
    exclude: [promote]

---

kind: pipeline
name: release

platform:
  os: linux
  arch: amd64

steps:
- name: notes
  image: golang:1.13-buster
  commands:
  - git fetch --tags
  - git log "$(git describe --tags --abbrev=0 HEAD~1)..HEAD" --oneline --format='%h %s' | tee -a notes.md
- name: build-linux-amd64
  image: docker.elastic.co/beats-dev/golang-crossbuild:1.13.8-main
  command: [
    "--platforms", "linux/amd64",
    "--build-cmd", "
      apt-get update -qqy && apt-get install -qqy swig &&
      CGO_ENABLED=1 go build -ldflags \"-s -w -linkmode external -X main.version=$(git describe --tags --always) -extldflags -static\" -o build/dictutil-linux-64bit ./cmd/dictutil &&
      CGO_ENABLED=1 go build -ldflags \"-s -w -linkmode external -X main.version=$(git describe --tags --always) -extldflags -static\" -o build/dictgen-linux-64bit ./cmd/dictgen &&
      CGO_ENABLED=1 go build -ldflags \"-s -w -linkmode external -X main.version=$(git describe --tags --always) -extldflags -static\" -o build/gotdict-convert-linux-64bit ./examples/gotdict-convert",
  ]
- name: build-linux-386
  image: docker.elastic.co/beats-dev/golang-crossbuild:1.13.8-main
  command: [
    "--platforms", "linux/amd64",
    "--build-cmd", "
      apt-get update -qqy && apt-get install -qqy swig &&
      CGO_ENABLED=1 go build -ldflags \"-s -w -linkmode external -X main.version=$(git describe --tags --always) -extldflags -static\" -o build/dictutil-linux-32bit ./cmd/dictutil &&
      CGO_ENABLED=1 go build -ldflags \"-s -w -linkmode external -X main.version=$(git describe --tags --always) -extldflags -static\" -o build/dictgen-linux-32bit ./cmd/dictgen &&
      CGO_ENABLED=1 go build -ldflags \"-s -w -linkmode external -X main.version=$(git describe --tags --always) -extldflags -static\" -o build/gotdict-convert-linux-32bit ./examples/gotdict-convert",
  ]
- name: build-linux-arm
  image: docker.elastic.co/beats-dev/golang-crossbuild:1.13.8-arm
  command: [
    "--platforms", "linux/armv6",
    "--build-cmd", "
      apt-get update -qqy && apt-get install -qqy swig &&
      CGO_ENABLED=1 go build -ldflags \"-s -w -linkmode external -X main.version=$(git describe --tags --always) -extldflags -static\" -o build/dictutil-linux-arm ./cmd/dictutil &&
      CGO_ENABLED=1 go build -ldflags \"-s -w -linkmode external -X main.version=$(git describe --tags --always) -extldflags -static\" -o build/dictgen-linux-arm ./cmd/dictgen &&
      CGO_ENABLED=1 go build -ldflags \"-s -w -linkmode external -X main.version=$(git describe --tags --always) -extldflags -static\" -o build/gotdict-convert-linux-arm ./examples/gotdict-convert",
  ]
- name: build-windows-386
  image: docker.elastic.co/beats-dev/golang-crossbuild:1.13.8-main
  command: [
    "--platforms", "windows/386",
    "--build-cmd", "
      apt-get update -qqy && apt-get install -qqy swig &&
      CGO_ENABLED=1 go build -ldflags \"-s -w -linkmode external -X main.version=$(git describe --tags --always) -extldflags -static\" -o build/dictutil-windows.exe ./cmd/dictutil &&
      CGO_ENABLED=1 go build -ldflags \"-s -w -linkmode external -X main.version=$(git describe --tags --always) -extldflags -static\" -o build/dictgen-windows.exe ./cmd/dictgen &&
      CGO_ENABLED=1 go build -ldflags \"-s -w -linkmode external -X main.version=$(git describe --tags --always) -extldflags -static\" -o build/gotdict-convert-windows.exe ./examples/gotdict-convert",
  ]
- name: build-darwin-amd64
  image: docker.elastic.co/beats-dev/golang-crossbuild:1.13.8-darwin
  command: [
    "--platforms", "darwin/amd64",
    "--build-cmd", "
      apt-get update -qqy && apt-get install -qqy swig &&
      CGO_ENABLED=1 go build -ldflags \"-s -w -linkmode external -X main.version=$(git describe --tags --always)\" -o build/dictutil-darwin-64bit ./cmd/dictutil &&
      CGO_ENABLED=1 go build -ldflags \"-s -w -linkmode external -X main.version=$(git describe --tags --always)\" -o build/dictgen-darwin-64bit ./cmd/dictgen &&
      CGO_ENABLED=1 go build -ldflags \"-s -w -linkmode external -X main.version=$(git describe --tags --always)\" -o build/gotdict-convert-darwin-64bit ./examples/gotdict-convert",
  ]
- name: list
  image: golang:1.13-buster
  commands:
  - ls -lah build
  depends_on: [build-linux-amd64, build-linux-arm, build-linux-386, build-windows-386, build-darwin-amd64]
- name: release
  image: plugins/github-release
  settings:
    api_key: {from_secret: GITHUB_TOKEN}
    title: ${DRONE_TAG}
    note: notes.md
    files: build/*
    draft: true
  when: {ref: {include: ["refs/tags/*"]}}
  depends_on: [notes, list]

depends_on:
- kobodict
- dictgen
- dictgen-cmd
- dictutil-cmd
- marisa
- gotdict-convert

trigger:
  event:
    exclude: [promote]
