name: kobodict
kind: pipeline
type: docker

steps:
- name: test
  image: golang:1.13-buster
  commands:
  - go test -cover -v ./kobodict
- name: bench
  image: golang:1.13-buster
  commands:
  - go test -bench=. -benchmem ./kobodict

trigger:
  event:
    exclude: [promote]

---

name: dictgen
kind: pipeline
type: docker

steps:
- name: test
  image: golang:1.13-buster
  commands:
  - go test -cover -v ./dictgen

trigger:
  event:
    exclude: [promote]

---

name: marisa
kind: pipeline
type: docker

steps:
- name: test
  image: golang:1.13-buster
  commands:
  - apt-get update -qqy && apt-get install -qqy swig libmarisa-dev
  - go test -v ./marisa

trigger:
  event:
    exclude: [promote]
